sudo: required

services:
    - docker

before_install:
    - docker build -t amitsaran/docker-todo-node -f Dockerfile.dev .

script:
    - docker run amitsaran/docker-todo-node npm test -- --coverage
